-- Add automation fields to products, if they do not already exist
ALTER TABLE IF EXISTS public.products
  ADD COLUMN IF NOT EXISTS automation_status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS automation_error text,
  ADD COLUMN IF NOT EXISTS content_generated_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_automated_at timestamptz,
  ADD COLUMN IF NOT EXISTS source_hash text,
  ADD COLUMN IF NOT EXISTS source_name text,
  ADD COLUMN IF NOT EXISTS source_url text;

-- Create automation_runs table to record imported/automation attempts
CREATE TABLE IF NOT EXISTS public.automation_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_type text NOT NULL,
  status text NOT NULL,
  products_checked integer DEFAULT 0,
  products_created integer DEFAULT 0,
  products_updated integer DEFAULT 0,
  products_skipped integer DEFAULT 0,
  products_failed integer DEFAULT 0,
  error_summary text,
  started_at timestamptz DEFAULT now(),
  completed_at timestamptz
);

-- Useful indexes
CREATE INDEX IF NOT EXISTS idx_products_source_hash ON public.products (source_hash);
CREATE INDEX IF NOT EXISTS idx_products_automation_status ON public.products (automation_status);
CREATE INDEX IF NOT EXISTS idx_automation_runs_started_at ON public.automation_runs (started_at);
